### ISSUE TITLE
Treemap wrapper implementation - Errors on some methods

### ISSUE THREAD

**Issue by lex-soft** [datanucleus/datanucleus-java8#1]
Hi,

I’m trying to store a TreeMap and everything seems all right as long as I avoid using some specific methods of TreeMap. 
It seems to happen with methods that were not overridden in the wrapper implementation of datanucleus.

I'm using datanucleus 5.0.3.

For instance, the problem arises using first-class java.util.TreeMap methods that have entry null-checks, like:
- getLowerEntry() which is called by lowerKey()
- exportEntry() which is called by lastEntry()

and so on.
These methods will always return null.

I could not narrow down the problem, but maybe this is enough to solve it.

Thank you for your work.
Alex

**Comment by lex-soft** [comment]
Sorry for posting this in the wrong section, it actually belongs to core. 
I'm new to github and don't know how to and even if i can move it to datanucleus-core.

**Comment by andyjefferson** [comment]
If you have a problem with a wrapper class then those are all in datanucleus-core (and GitHub doesn't allow moving of issues sadly). Besides, you could easily enough contribute an override of such a method after seeing if it works. I don't have time for such things and the only way that such projects will continue is if people get involved.
